version: '3.8'

services:
  frontend:
    build:
      context: ./FrontSamar  # Path to frontend directory
      dockerfile: Dockerfile  # Frontend Dockerfile
    image: samarfrontend:latest  # Custom image name for the frontend
    volumes:
      - ./FrontSamar:/app
    ports:
      - "3000:3000"
    networks:
      - app_network
    depends_on:
      - backend

  backend:
    build:
      context: ./BackSamar  # Path to backend directory
      dockerfile: Dockerfile  # Backend Dockerfile
    image: backendsamar:latest  # Custom image name for the backend
    volumes:
      - ./BackSamar:/app
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: nouchka/sqlite3:latest  # SQLite database container (replace with your DB image if needed)
    volumes:
      - ./BackSamar/db.sqlite3:/app/db.sqlite3
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
